# Generated by Django 5.2.17 on 2026-09-11 23:27

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mizan.platform.db.models
import mizan.platform.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0002_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("token", models.CharField(db_index=True, max_length=32)),
                (
                    "short_code_given",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("FOUND", "Found"),
                            ("NOT_FOUND", "Not found"),
                            ("DIGEST_OK", "Digest returned"),
                            ("DIGEST_BAD", "Wrong short code"),
                            ("REVOKED_LOOKUP", "Lookup of a revoked document"),
                            ("RATE_LIMITED", "Rate limited"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "verification_attempt",
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("kind", mizan.platform.db.models.CodeField(max_length=64)),
                ("locale", models.CharField(default="fr", max_length=8)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("html", models.TextField()),
                ("css", models.TextField(blank=True, default="")),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("sample_data", models.JSONField(blank=True, default=dict)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "document_template",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="IssuedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("kind", mizan.platform.db.models.CodeField(max_length=64)),
                ("number", models.CharField(max_length=64)),
                (
                    "subject_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("subject", models.JSONField(blank=True, default=dict)),
                ("digest", models.JSONField(blank=True, default=dict)),
                ("render_data", models.JSONField(blank=True, default=dict)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("issued_by", models.UUIDField(blank=True, null=True)),
                ("template_version", models.PositiveIntegerField(default=0)),
                ("locale", models.CharField(default="fr", max_length=8)),
                ("content_hash", models.CharField(max_length=64)),
                ("pdf_object_key", models.CharField(max_length=255)),
                ("pdf_sha256", models.CharField(max_length=64)),
                ("pdf_size", models.PositiveIntegerField(default=0)),
                ("seal_level", models.CharField(default="B-B", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                ("revoked_reason", models.TextField(blank=True, default="")),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("verify_token", models.CharField(max_length=32, unique=True)),
                ("short_code", models.CharField(max_length=8)),
                ("qr_jws", models.TextField(blank=True, default="")),
                (
                    "transparency_leaf_index",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        to="org.branch",
                    ),
                ),
                (
                    "signatory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.signatory",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.issueddocument",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documenttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "issued_document",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FraudCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("token", models.CharField(blank=True, default="", max_length=32)),
                (
                    "reporter_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "reporter_contact",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "attachment_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("state", models.CharField(default="OPEN", max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fraud_cases",
                        to="documents.issueddocument",
                    ),
                ),
            ],
            options={
                "db_table": "fraud_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("kind", mizan.platform.db.models.CodeField(max_length=64)),
                ("defaults", models.JSONField(default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_profiles",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "print_profile",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Rendition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                ("produced_by", models.UUIDField(blank=True, null=True)),
                (
                    "produced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("object_key", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="documents.issueddocument",
                    ),
                ),
            ],
            options={
                "db_table": "rendition",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SigningKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("QR", "QR payload signing (Ed25519)"),
                            ("PDF", "PDF sealing (RSA-3072 / X.509)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("kid", models.CharField(max_length=64, unique=True)),
                ("algorithm", models.CharField(max_length=32)),
                ("backend", models.CharField(default="local", max_length=16)),
                ("key_ref", models.CharField(max_length=255)),
                ("public_jwk", models.JSONField(blank=True, default=dict)),
                ("certificate_pem", models.TextField(blank=True, default="")),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired (still valid for verification)"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_keys",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "signing_key",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="issueddocument",
            name="qr_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.signingkey",
            ),
        ),
        migrations.AddField(
            model_name="issueddocument",
            name="seal_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.signingkey",
            ),
        ),
        migrations.CreateModel(
            name="TransparencyHead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("tree_size", models.BigIntegerField()),
                ("root_hash", models.CharField(max_length=64)),
                ("signature", models.TextField()),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.signingkey",
                    ),
                ),
            ],
            options={
                "db_table": "transparency_head",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TransparencyLeaf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("index", models.BigIntegerField()),
                ("leaf_hash", models.CharField(max_length=64)),
                ("tree_head_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transparency_leaf",
                        to="documents.issueddocument",
                    ),
                ),
            ],
            options={
                "db_table": "transparency_leaf",
                "ordering": ["index"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "branch", "kind", "locale", "version"),
                name="uq_document_template_version",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="printprofile",
            constraint=models.UniqueConstraint(
                fields=("branch", "kind"), name="uq_print_profile"
            ),
        ),
        migrations.AddIndex(
            model_name="issueddocument",
            index=models.Index(
                fields=["tenant_id", "kind", "number"],
                name="idx_issued_document_number",
            ),
        ),
        migrations.AddIndex(
            model_name="issueddocument",
            index=models.Index(
                fields=["subject_type", "subject_id"],
                name="idx_issued_document_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="transparencyleaf",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "index"), name="uq_transparency_leaf_index"
            ),
        ),
    ]
