# Generated by Django 5.2.17 on 2026-09-11 21:24

import django.db.models.functions.text
import django.utils.timezone
import mizan.platform.ids
import mizan.platform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="I18nText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, default=mizan.platform.models._default_tenant_id
                    ),
                ),
                ("entity", models.CharField(max_length=64)),
                ("entity_id", models.UUIDField()),
                ("field", models.CharField(default="label", max_length=32)),
                ("locale", models.CharField(max_length=8)),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "i18n_text",
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"], name="idx_i18n_text_entity"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "entity", "entity_id", "field", "locale"),
                        name="uq_i18n_text_key",
                    ),
                    models.UniqueConstraint(
                        models.F("tenant_id"),
                        models.F("entity"),
                        models.F("field"),
                        models.F("locale"),
                        django.db.models.functions.text.Lower("text"),
                        condition=models.Q(("field", "label")),
                        name="uq_i18n_label",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, default=mizan.platform.models._default_tenant_id
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "idempotency_key",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "key"), name="uq_idempotency_key"
                    )
                ],
            },
        ),
    ]
