# Generated by Django 5.2.17 on 2026-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0002_extensions_and_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="i18ntext",
            name="entity",
            field=models.CharField(max_length=200),
        ),
    ]
