# Generated by Django 5.2.17 on 2026-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0003_widen_i18n_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicJobRun",
            fields=[
                (
                    "name",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("failures", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "periodic_job_run",
            },
        ),
    ]
