# Generated by Django 5.2.17 on 2026-09-11 22:49

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mizan.apps.config.models
import mizan.platform.db.models
import mizan.platform.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0002_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberingScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("ACCOUNT", "Account"),
                            ("PROJECT", "Project"),
                            ("QUOTE", "Quote"),
                            ("ORDER", "Order"),
                            ("CONTRACT", "Contract"),
                            ("INTAKE", "Intake"),
                            ("SAMPLE", "Sample"),
                            ("SPECIMEN", "Specimen"),
                            ("TEST_RUN", "Test run"),
                            ("REPORT", "Report"),
                            ("INVOICE", "Invoice"),
                            ("CREDIT_NOTE", "Credit note"),
                            ("PAYMENT", "Payment"),
                            ("RENTAL", "Rental"),
                            ("SALE", "Sale"),
                            ("OUTING", "Outing"),
                            ("TRANSFER", "Transfer"),
                            ("WORK_ORDER", "Work order"),
                            ("EQUIPMENT", "Equipment"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("prefix", models.CharField(blank=True, default="", max_length=16)),
                ("pattern", models.CharField(max_length=120)),
                (
                    "reset",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("YEARLY", "Yearly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="YEARLY",
                        max_length=16,
                    ),
                ),
                (
                    "gap_policy",
                    models.CharField(
                        choices=[("GAP_FREE", "Gap-free"), ("TOLERANT", "Tolerant")],
                        default="TOLERANT",
                        max_length=16,
                    ),
                ),
                (
                    "allocation",
                    models.CharField(
                        choices=[("ON_CREATE", "On create"), ("ON_ISSUE", "On issue")],
                        default="ON_CREATE",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("immutable", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbering_schemes",
                        to="org.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbering_schemes",
                        to="org.department",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="config.numberingscheme",
                    ),
                ),
            ],
            options={
                "db_table": "numbering_scheme",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NumberingCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.apps.config.models._default_tenant_id,
                    ),
                ),
                ("period_key", models.CharField(default="", max_length=16)),
                ("value", models.BigIntegerField(default=0)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="config.numberingscheme",
                    ),
                ),
            ],
            options={
                "db_table": "numbering_counter",
            },
        ),
        migrations.CreateModel(
            name="NumberReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.apps.config.models._default_tenant_id,
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                ("reserved_by", models.UUIDField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="config.numberingscheme",
                    ),
                ),
            ],
            options={
                "db_table": "number_reservation",
            },
        ),
        migrations.CreateModel(
            name="PaymentTermsTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("milestones", models.JSONField(default=list)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_terms_templates",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "payment_terms_template",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("currency", models.CharField(max_length=3)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("account_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "price_list",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("ord", models.PositiveIntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.department",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="config.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "service_category",
                "ordering": ["ord", "code"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LAB_TEST", "Laboratory test"),
                            ("FIELD_SERVICE", "Field service"),
                            ("STUDY", "Study"),
                            ("RENTAL", "Rental"),
                            ("SALE", "Sale"),
                            ("FEE", "Fee"),
                        ],
                        max_length=16,
                    ),
                ),
                ("unit_of_sale", models.CharField(default="UNIT", max_length=32)),
                (
                    "test_definition_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase_template_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "equipment_class_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "stock_item_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.department",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="config.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "service",
                "ordering": ["code"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SieveSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("sizes_mm", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sieve_set",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code"), name="uq_sieve_set_code"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SpecimenType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("shape", models.CharField(max_length=16)),
                ("dims", models.JSONField(default=dict)),
                ("derived", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "specimen_type",
                "ordering": ["code"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code"), name="uq_specimen_type_code"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "min_qty",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="config.pricelist",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="config.service",
                    ),
                ),
                (
                    "specimen_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="config.specimentype",
                    ),
                ),
            ],
            options={
                "db_table": "price",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("applies_to_kinds", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_rules",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "tax_rule",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "method_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("unit_under_test", models.CharField(max_length=16)),
                ("specimen_type_codes", models.JSONField(blank=True, default=list)),
                ("scheduling", models.JSONField(default=dict)),
                ("stages", models.JSONField(default=list)),
                ("intake_fields", models.JSONField(blank=True, default=list)),
                ("inputs", models.JSONField(default=list)),
                ("computed", models.JSONField(default=list)),
                ("aggregates", models.JSONField(blank=True, default=list)),
                ("rules", models.JSONField(blank=True, default=list)),
                (
                    "required_equipment_class_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "report_template_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("report_columns", models.JSONField(blank=True, default=list)),
                (
                    "unit_of_sale",
                    models.CharField(default="PER_SPECIMEN", max_length=32),
                ),
                ("locked", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="config.servicecategory",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.department",
                    ),
                ),
            ],
            options={
                "db_table": "test_definition",
                "ordering": ["code", "-version"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="VocabularyEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=48)),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("colour", models.CharField(blank=True, default="", max_length=32)),
                ("icon", models.CharField(blank=True, default="", max_length=48)),
                ("ord", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "vocabulary_entry",
                "ordering": ["kind", "ord", "code"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="pricelist",
            name="client_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="config.vocabularyentry",
            ),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "workflow",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("semantic", models.CharField(max_length=32)),
                ("colour", models.CharField(default="slate", max_length=32)),
                ("is_initial", models.BooleanField(default=False)),
                ("is_terminal", models.BooleanField(default=False)),
                ("sla_days", models.PositiveIntegerField(blank=True, null=True)),
                ("ord", models.PositiveIntegerField(default=0)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="config.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_state",
                "ordering": ["ord", "code"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("required_action", models.CharField(max_length=64)),
                ("guards", models.JSONField(blank=True, default=list)),
                ("effects", models.JSONField(blank=True, default=list)),
                ("ord", models.PositiveIntegerField(default=0)),
                (
                    "from_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_out",
                        to="config.workflowstate",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_in",
                        to="config.workflowstate",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="config.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_transition",
                "ordering": ["ord"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="numberingscheme",
            constraint=models.UniqueConstraint(
                fields=("branch", "department", "applies_to", "version"),
                name="uq_numbering_scheme_version",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="numberingcounter",
            constraint=models.UniqueConstraint(
                fields=("scheme", "period_key"), name="uq_numbering_counter"
            ),
        ),
        migrations.AddConstraint(
            model_name="numberreservation",
            constraint=models.UniqueConstraint(
                fields=("scheme", "number"), name="uq_number_reservation"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttermstemplate",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="uq_payment_terms_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "code"), name="uq_service_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "code"), name="uq_service_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                fields=("price_list", "service", "specimen_type", "min_qty"),
                name="uq_price_row",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrule",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="uq_tax_rule_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="testdefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "code", "version"),
                name="uq_test_definition_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabularyentry",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "branch", "kind", "code"),
                name="uq_vocabulary_entry",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="uq_price_list_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "branch", "kind", "version"),
                name="uq_workflow_version",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstate",
            constraint=models.UniqueConstraint(
                fields=("workflow", "code"), name="uq_workflow_state_code"
            ),
        ),
    ]
