# Generated by Django 5.2.17 on 2026-09-12 04:13

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mizan.platform.db.models
import mizan.platform.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0002_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactChannelPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("user", "Staff or portal user"),
                            ("contact", "Client contact"),
                        ],
                        default="contact",
                        max_length=16,
                    ),
                ),
                ("recipient_id", models.UUIDField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-app (SSE + inbox, portal)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "contact_channel_preference",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant_id",
                            "recipient_type",
                            "recipient_id",
                            "channel",
                        ),
                        name="uq_contact_channel_preference",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("locale", models.CharField(default="fr", max_length=8)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-app (SSE + inbox, portal)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=300)),
                ("body", models.TextField()),
                ("html", models.TextField(blank=True, default="")),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "message_template",
                "ordering": ["code", "channel", "locale"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code", "locale", "channel"),
                        name="uq_message_template",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                (
                    "event_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("template_code", mizan.platform.db.models.CodeField(max_length=64)),
                ("throttle", models.JSONField(blank=True, default=dict)),
                ("digest", models.JSONField(blank=True, default=dict)),
                ("respect_quiet_hours", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "notification_rule",
                "ordering": ["code"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("event_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "event_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("recipient", models.JSONField(default=dict)),
                ("recipient_key", models.CharField(db_index=True, max_length=120)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-app (SSE + inbox, portal)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("locale", models.CharField(default="fr", max_length=8)),
                (
                    "template_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("rendered", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCHEDULED", "Scheduled (quiet hours)"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("dedupe_key", models.CharField(max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.branch",
                    ),
                ),
                (
                    "fallback_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallbacks",
                        to="notify.notificationdelivery",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="notify.notificationrule",
                    ),
                ),
            ],
            options={
                "db_table": "notification_delivery",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("event_id", models.UUIDField(blank=True, null=True)),
                ("event_code", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True, default="")),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notify.notificationdelivery",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(
                        fields=["user", "read_at", "created_at"],
                        name="idx_notification_user_unread",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="notificationrule",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "branch", "code"),
                name="uq_notification_rule_code",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["tenant_id", "recipient_key", "created_at"],
                name="idx_notification_delivery_rcpt",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "dedupe_key"),
                name="uq_notification_delivery_dedupe",
            ),
        ),
    ]
