# Generated by Django 5.2.17 on 2026-09-11 21:24

import django.db.models.functions.text
import django.utils.timezone
import mizan.apps.identity.models
import mizan.platform.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "idp_subject",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("locale", models.CharField(default="fr", max_length=8)),
                (
                    "realm",
                    models.CharField(
                        choices=[
                            ("STAFF", "Staff"),
                            ("CLIENT", "Client"),
                            ("PLATFORM", "Platform operator"),
                        ],
                        default="STAFF",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("mfa_enrolled", models.BooleanField(default=False)),
                ("must_change_password", models.BooleanField(default=False)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Access to the platform operator console",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "app_user",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("tenant_id"),
                        django.db.models.functions.text.Lower("email"),
                        name="uq_app_user_email_per_tenant",
                        nulls_distinct=False,
                    )
                ],
            },
            managers=[
                ("objects", mizan.apps.identity.models.UserManager()),
            ],
        ),
    ]
