# Generated by Django 5.2.17 on 2026-09-11 21:36

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mizan.platform.db.models
import mizan.platform.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_rls"),
        ("org", "0002_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("session_id", models.UUIDField(db_index=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refresh_token",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("is_template", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETIRED", "Retired")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "role",
                "ordering": ["code"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code"), name="uq_role_code"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("account_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("project_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="org.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="org.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="identity.role",
                    ),
                ),
            ],
            options={
                "db_table": "membership",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("hashed_key", models.CharField(max_length=64, unique=True)),
                ("prefix", models.CharField(max_length=12)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_keys",
                        to="identity.role",
                    ),
                ),
            ],
            options={
                "db_table": "api_key",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("resource", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("scope", models.CharField(max_length=32)),
                ("field_groups", models.JSONField(blank=True, default=list)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="identity.role",
                    ),
                ),
            ],
            options={
                "db_table": "grant_",
                "ordering": ["resource", "action"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "resource", "action", "scope"),
                        name="uq_grant_role_resource_action",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
