# Generated by Django 5.2.17 on 2026-09-11 21:24

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mizan.platform.db.models
import mizan.platform.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "code",
                    mizan.platform.db.models.CodeField(max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("theme", models.JSONField(blank=True, default=dict)),
                ("plan", models.CharField(default="standard", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "tenant",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("legal_name", models.CharField(max_length=200)),
                (
                    "trade_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("identifiers", models.JSONField(blank=True, default=dict)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("currency", models.CharField(max_length=3)),
                (
                    "timezone",
                    models.CharField(default="Africa/Nouakchott", max_length=64),
                ),
                ("locales", models.JSONField(blank=True, default=list)),
                ("default_locale", models.CharField(default="fr", max_length=8)),
                ("rounding", models.CharField(default="HALF_UP_2", max_length=16)),
                ("working_days", models.JSONField(blank=True, default=list)),
                ("holidays", models.JSONField(blank=True, default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("legal_texts", models.JSONField(blank=True, default=dict)),
                (
                    "logo_object_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "branch",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code"), name="uq_branch_code"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Signatory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("document_kinds", models.JSONField(blank=True, default=list)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Signature image"),
                            ("DRAWN", "Drawn on device"),
                            ("DIGITAL_CERTIFICATE", "Personal digital certificate"),
                            ("EXTERNAL_ESIGN", "External e-signature provider"),
                        ],
                        default="IMAGE",
                        max_length=32,
                    ),
                ),
                (
                    "signature_image_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stamp_image_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("image_positions", models.JSONField(blank=True, default=dict)),
                ("image_version", models.PositiveIntegerField(default=0)),
                ("image_approved_by", models.UUIDField(blank=True, null=True)),
                ("image_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certificate_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "esign_provider_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("requires_step_up", models.BooleanField(default=True)),
                ("signing_order", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatories",
                        to="org.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "signatory",
                "ordering": ["signing_order", "display_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TreasuryAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BANK", "Bank"), ("CASH", "Cash")], max_length=8
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("bank_name", models.CharField(blank=True, default="", max_length=200)),
                ("iban", models.CharField(blank=True, default="", max_length=64)),
                ("bic", models.CharField(blank=True, default="", max_length=16)),
                ("currency", models.CharField(max_length=3)),
                ("printed_on_invoices", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treasury_accounts",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "treasury_account",
                "ordering": ["type", "label"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deleted_reason",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("row_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        default=mizan.platform.db.models._default_tenant_id,
                        editable=False,
                    ),
                ),
                ("code", mizan.platform.db.models.CodeField(max_length=64)),
                ("colour", models.CharField(blank=True, default="", max_length=32)),
                ("ord", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "db_table": "department",
                "ordering": ["ord", "code"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "code"), name="uq_department_code"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
