# Generated by Django 5.2.17 on 2026-09-11 22:00

import django.utils.timezone
import mizan.apps.audit.models
import mizan.platform.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mizan.platform.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=mizan.apps.audit.models._default_tenant_id,
                        null=True,
                    ),
                ),
                ("branch_id", models.UUIDField(blank=True, null=True)),
                ("aggregate_type", models.CharField(max_length=64)),
                ("aggregate_id", models.UUIDField(blank=True, null=True)),
                ("action", models.CharField(max_length=64)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("actor_type", models.CharField(default="SYSTEM", max_length=16)),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "at"],
                        name="idx_audit_aggregate",
                    ),
                    models.Index(
                        fields=["tenant_id", "at"], name="idx_audit_tenant_at"
                    ),
                    models.Index(fields=["actor_id", "at"], name="idx_audit_actor_at"),
                ],
            },
        ),
    ]
